<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Recipe;
use App\Models\User;
use App\Models\Category;
use App\Models\Region;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run()
    {
        // Create user
        $user = User::firstOrCreate(
            ['email' => 'test@example.com'],
            [
                'name' => 'Test User',
                'password' => bcrypt('password'),
            ]
        );

        // Create categories
        $categories = [
            'west' => Category::firstOrCreate(['name' => 'West']),
            'southWest' => Category::firstOrCreate(['name' => 'South West']),
            'westAfrican' => Category::firstOrCreate(['name' => 'West African']),
            'international' => Category::firstOrCreate(['name' => 'International']),
            'snacks' => Category::firstOrCreate(['name' => 'Snacks']),
            'drinks' => Category::firstOrCreate(['name' => 'Drinks']),
            'northWest' => Category::firstOrCreate(['name' => 'North West']),
            'littoral' => Category::firstOrCreate(['name' => 'Littoral']),
            'centralAfrican' => Category::firstOrCreate(['name' => 'Central African']),
            'eastAfrican' => Category::firstOrCreate(['name' => 'East African']),
            'southAfrican' => Category::firstOrCreate(['name' => 'South African']),
            'desserts' => Category::firstOrCreate(['name' => 'Desserts']),
            'northAfrican' => Category::firstOrCreate(['name' => 'North African']),
            'centre' => Category::firstOrCreate(['name' => 'Centre']),
            'east' => Category::firstOrCreate(['name' => 'East']),
            'breakfasts' => Category::firstOrCreate(['name' => 'Breakfasts']),
        ];

        // Create regions
        $regions = [
            'centre' => Region::firstOrCreate(['name' => 'Centre']),
            'southwest' => Region::firstOrCreate(['name' => 'Southwest']),
            'westAfrican' => Region::firstOrCreate(['name' => 'West African']),
            'northwest' => Region::firstOrCreate(['name' => 'Northwest']),
            'littoral' => Region::firstOrCreate(['name' => 'Littoral']),
            'north' => Region::firstOrCreate(['name' => 'North']),
            'centralAfrican' => Region::firstOrCreate(['name' => 'Central African']),
            'eastAfrican' => Region::firstOrCreate(['name' => 'East African']),
            'southAfrican' => Region::firstOrCreate(['name' => 'South African']),
            'international' => Region::firstOrCreate(['name' => 'International']),
            'senegal' => Region::firstOrCreate(['name' => 'Senegal']),
            'nigeria' => Region::firstOrCreate(['name' => 'Nigeria']),
            'east' => Region::firstOrCreate(['name' => 'East']),
            'adamawa' => Region::firstOrCreate(['name' => 'Adamawa']),
            'somalia' => Region::firstOrCreate(['name' => 'Somalia']),
            'kenya' => Region::firstOrCreate(['name' => 'Kenya']),
            'mozambique' => Region::firstOrCreate(['name' => 'Mozambique']),
            'morocco' => Region::firstOrCreate(['name' => 'Morocco']),
            'ghana' => Region::firstOrCreate(['name' => 'Ghana']),
            'india' => Region::firstOrCreate(['name' => 'India']),
            'algeria' => Region::firstOrCreate(['name' => 'Algeria']),
            'west' => Region::firstOrCreate(['name' => 'west']),
            'vietnam' => Region::firstOrCreate(['name' => 'Vietnam']),
            'pakistan' => Region::firstOrCreate(['name' => 'Pakistan']),
        ];

        // Seed recipes
        $recipes = [
            [
                'title' => 'Ndole',
                'description' => 'A bitterleaf stew with peanuts and meat.',
                'ingredients' => json_encode(['bitterleaf', 'peanuts', 'beef', 'onions', 'palm oil']),
                'steps' => json_encode(['Wash bitterleaf thoroughly.', 'Boil beef with onions.', 'Grind peanuts and add to stew.', 'Simmer with palm oil.']),
                'category_id' => $categories['west']->id,
                'region_id' => $regions['centre']->id,
                'min_price' => '1000',
                'cook_time' => '60 min',
                'prep_time' => '30 min',
                'image_path' => 'recipes/Ndole-1.webp',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Eru',
                'description' => 'A flavorful mix of green leaves and water fufu.',
                'ingredients' => json_encode(['eru leaves', 'waterleaf', 'palm oil', 'crayfish', 'cow skin']),
                'steps' => json_encode(['Boil eru and waterleaf.', 'Add palm oil and crayfish.', 'Simmer with cow skin.', 'Serve with water fufu.']),
                'category_id' => $categories['southWest']->id,
                'region_id' => $regions['southwest']->id,
                'min_price' => '800',
                'cook_time' => '45 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/Eru.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'welcome',
            ],
            [
                'title' => 'Jollof Rice',
                'description' => 'Classic West African rice cooked in spicy tomato sauce.',
                'ingredients' => json_encode(['rice', 'tomatoes', 'peppers', 'onions', 'chicken']),
                'steps' => json_encode(['Blend tomatoes and peppers.', 'Fry onions and paste.', 'Add rice and stock.', 'Cook until tender.']),
                'category_id' => $categories['westAfrican']->id,
                'region_id' => $regions['westAfrican']->id,
                'min_price' => '700',
                'cook_time' => '40 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/jolof-rice.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Fufu & Light Soup',
                'description' => 'Ghanaian fufu served with spicy light soup.',
                'ingredients' => json_encode(['cassava', 'plantain', 'tomatoes', 'goat meat', 'ginger']),
                'steps' => json_encode(['Boil cassava and plantain.', 'Pound into fufu.', 'Cook tomatoes and goat meat.', 'Add spices and simmer.']),
                'category_id' => $categories['westAfrican']->id,
                'region_id' => $regions['westAfrican']->id,
                'min_price' => '900',
                'cook_time' => '50 min',
                'prep_time' => '25 min',
                'image_path' => 'recipes/Fufu-light-soup.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Spaghetti Bolognese',
                'description' => 'Italian classic with rich meat sauce.',
                'ingredients' => json_encode(['spaghetti', 'ground beef', 'tomatoes', 'onions', 'parmesan']),
                'steps' => json_encode(['Boil spaghetti.', 'Cook beef with onions.', 'Add tomato sauce.', 'Serve with parmesan.']),
                'category_id' => $categories['international']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '1200',
                'cook_time' => '30 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/spaghetti-bolognese.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Chicken Curry',
                'description' => 'Aromatic curry with tender chicken pieces.',
                'ingredients' => json_encode(['chicken', 'curry powder', 'coconut milk', 'onions', 'garlic']),
                'steps' => json_encode(['Marinate chicken with spices.', 'Fry onions and garlic.', 'Add coconut milk.', 'Simmer until cooked.']),
                'category_id' => $categories['international']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '1100',
                'cook_time' => '35 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/chickencurry.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Puff Puff',
                'description' => 'A local breakfast with a beautiful texture.',
                'ingredients' => json_encode(['flour', 'sugar', 'yeast', 'water', 'oil']),
                'steps' => json_encode(['Mix flour, sugar, and yeast.', 'Add water to form dough.', 'Fry in hot oil.', 'Drain and serve.']),
                'category_id' => $categories['snacks']->id,
                'region_id' => $regions['centre']->id,
                'min_price' => '200',
                'cook_time' => '20 min',
                'prep_time' => '10 min',
                'image_path' => 'recipes/puff-puff.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Folere',
                'description' => 'Local refreshing drink to brighten your day.',
                'ingredients' => json_encode(['hibiscus flowers', 'sugar', 'water', 'ginger', 'pineapple']),
                'steps' => json_encode(['Boil hibiscus flowers.', 'Add sugar and ginger.', 'Strain and cool.', 'Serve chilled.']),
                'category_id' => $categories['drinks']->id,
                'region_id' => $regions['centre']->id,
                'min_price' => '300',
                'cook_time' => '15 min',
                'prep_time' => '10 min',
                'image_path' => 'recipes/Folere.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Achu Soup',
                'description' => 'Yellow soup served with pounded cocoyam.',
                'ingredients' => json_encode(['cocoyam', 'palm oil', 'limestone', 'beef', 'spices']),
                'steps' => json_encode(['Pound cocoyam.', 'Boil beef with spices.', 'Mix limestone and palm oil.', 'Combine and serve.']),
                'category_id' => $categories['northWest']->id,
                'region_id' => $regions['northwest']->id,
                'min_price' => '1000',
                'cook_time' => '60 min',
                'prep_time' => '30 min',
                'image_path' => 'recipes/achu.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Mbongo Tchobi',
                'description' => 'Black sauce made from burnt spices and fish.',
                'ingredients' => json_encode(['fish', 'mbongo spice', 'tomatoes', 'onions', 'palm oil']),
                'steps' => json_encode(['Burn mbongo spice.', 'Fry onions and tomatoes.', 'Add fish and palm oil.', 'Simmer and serve.']),
                'category_id' => $categories['littoral']->id,
                'region_id' => $regions['littoral']->id,
                'min_price' => '900',
                'cook_time' => '40 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/mbongo.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Kilishi',
                'description' => 'Spicy dried meat snack from the north.',
                'ingredients' => json_encode(['beef', 'peanuts', 'spices', 'salt', 'ginger']),
                'steps' => json_encode(['Slice beef thinly.', 'Marinate with spices.', 'Dry in sun or oven.', 'Grind peanuts and coat.']),
                'category_id' => $categories['snacks']->id,
                'region_id' => $regions['north']->id,
                'min_price' => '500',
                'cook_time' => '120 min',
                'prep_time' => '30 min',
                'image_path' => 'recipes/kilishi.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Kati Kati',
                'description' => 'Grilled chicken with palm oil and huckleberry.',
                'ingredients' => json_encode(['chicken', 'huckleberry', 'palm oil', 'onions', 'spices']),
                'steps' => json_encode(['Marinate chicken.', 'Grill until cooked.', 'Cook huckleberry with palm oil.', 'Serve together.']),
                'category_id' => $categories['northWest']->id,
                'region_id' => $regions['northwest']->id,
                'min_price' => '1000',
                'cook_time' => '45 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/kati.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Makayabu',
                'description' => 'Salted fish with vegetables, popular in Central Africa.',
                'ingredients' => json_encode(['salted fish', 'onions', 'tomatoes', 'peppers', 'oil']),
                'steps' => json_encode(['Soak fish to reduce salt.', 'Fry onions and peppers.', 'Add tomatoes and fish.', 'Simmer and serve.']),
                'category_id' => $categories['centralAfrican']->id,
                'region_id' => $regions['centralAfrican']->id,
                'min_price' => '800',
                'cook_time' => '30 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/makayabu.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Mandazi',
                'description' => 'East African fried dough snack.',
                'ingredients' => json_encode(['flour', 'sugar', 'coconut milk', 'yeast', 'oil']),
                'steps' => json_encode(['Mix flour, sugar, and yeast.', 'Add coconut milk.', 'Knead and fry.', 'Drain and serve.']),
                'category_id' => $categories['snacks']->id,
                'region_id' => $regions['eastAfrican']->id,
                'min_price' => '200',
                'cook_time' => '20 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/mandazi.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Chakalaka',
                'description' => 'Spicy vegetable relish from South Africa.',
                'ingredients' => json_encode(['beans', 'peppers', 'carrots', 'tomatoes', 'spices']),
                'steps' => json_encode(['Chop vegetables.', 'Fry peppers and carrots.', 'Add beans and spices.', 'Simmer and serve.']),
                'category_id' => $categories['southAfrican']->id,
                'region_id' => $regions['southAfrican']->id,
                'min_price' => '400',
                'cook_time' => '25 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/chakalaka.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Chocolate Cake',
                'description' => 'Decadent dessert with a gooey chocolate center.',
                'ingredients' => json_encode(['flour', 'cocoa', 'sugar', 'eggs', 'butter']),
                'steps' => json_encode(['Mix dry ingredients.', 'Add eggs and butter.', 'Bake at 180°C.', 'Cool and serve.']),
                'category_id' => $categories['desserts']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '1500',
                'cook_time' => '40 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/chococake.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Fruit Salad',
                'description' => 'Fresh fruits served with chilled yogurt.',
                'ingredients' => json_encode(['mango', 'banana', 'pineapple', 'yogurt', 'honey']),
                'steps' => json_encode(['Chop fruits.', 'Mix with yogurt.', 'Drizzle honey.', 'Chill and serve.']),
                'category_id' => $categories['desserts']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '600',
                'cook_time' => '0 min',
                'prep_time' => '10 min',
                'image_path' => 'recipes/fruitsalad.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Yassa',
                'description' => 'A Senegalese dish made with marinated chicken or fish.',
                'ingredients' => json_encode(['chicken', 'onions', 'mustard', 'lemon', 'rice']),
                'steps' => json_encode(['Marinate chicken with mustard.', 'Fry onions.', 'Add chicken and lemon.', 'Serve with rice.']),
                'category_id' => $categories['westAfrican']->id,
                'region_id' => $regions['senegal']->id,
                'min_price' => '1000',
                'cook_time' => '45 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/yassa.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Egusi Soup',
                'description' => 'Ground melon seed soup with vegetables and meat.',
                'ingredients' => json_encode(['egusi seeds', 'spinach', 'beef', 'palm oil', 'crayfish']),
                'steps' => json_encode(['Grind egusi seeds.', 'Boil beef.', 'Fry palm oil with egusi.', 'Add spinach and serve.']),
                'category_id' => $categories['westAfrican']->id,
                'region_id' => $regions['nigeria']->id,
                'min_price' => '900',
                'cook_time' => '50 min',
                'prep_time' => '25 min',
                'image_path' => 'recipes/egusi.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Shawarma',
                'description' => 'Middle Eastern wrap with spiced meat.',
                'ingredients' => json_encode(['chicken', 'pita bread', 'garlic sauce', 'lettuce', 'tomatoes']),
                'steps' => json_encode(['Marinate chicken.', 'Grill meat.', 'Assemble in pita.', 'Add sauce and serve.']),
                'category_id' => $categories['international']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '700',
                'cook_time' => '20 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/shawarma.png',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Okok',
                'description' => 'Cassava leaves cooked with peanuts and palm oil.',
                'ingredients' => json_encode(['cassava leaves', 'peanuts', 'palm oil', 'fish', 'spices']),
                'steps' => json_encode(['Boil cassava leaves.', 'Grind peanuts.', 'Add palm oil and fish.', 'Simmer and serve.']),
                'category_id' => $categories['east']->id,
                'region_id' => $regions['east']->id,
                'min_price' => '800',
                'cook_time' => '50 min',
                'prep_time' => '25 min',
                'image_path' => 'recipes/okok.webp',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Sanga',
                'description' => 'A traditional dish made with fresh corn and cassava leaves.',
                'ingredients' => json_encode(['corn', 'cassava leaves', 'palm oil', 'onions', 'spices']),
                'steps' => json_encode(['Grind corn.', 'Boil cassava leaves.', 'Mix with palm oil.', 'Cook and serve.']),
                'category_id' => $categories['centre']->id,
                'region_id' => $regions['centre']->id,
                'min_price' => '600',
                'cook_time' => '40 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/sanga.webp',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Yaourt',
                'description' => 'Fermented milk, a Fulani traditional drink.',
                'ingredients' => json_encode(['milk', 'starter culture', 'sugar']),
                'steps' => json_encode(['Heat milk.', 'Add starter culture.', 'Ferment overnight.', 'Sweeten and serve.']),
                'category_id' => $categories['drinks']->id,
                'region_id' => $regions['adamawa']->id,
                'min_price' => '300',
                'cook_time' => '0 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/Yaourt.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Lahoh with Suqaar',
                'description' => 'Somali spongy bread served with stir-fried meat.',
                'ingredients' => json_encode(['flour', 'water', 'beef', 'spices', 'onions']),
                'steps' => json_encode(['Mix flour and water.', 'Cook lahoh on griddle.', 'Stir-fry beef with spices.', 'Serve together.']),
                'category_id' => $categories['eastAfrican']->id,
                'region_id' => $regions['somalia']->id,
                'min_price' => '900',
                'cook_time' => '30 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/lahoh.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Nyama Choma',
                'description' => 'Kenyan roasted meat often enjoyed with kachumbari.',
                'ingredients' => json_encode(['goat meat', 'salt', 'tomatoes', 'onions', 'chili']),
                'steps' => json_encode(['Marinate meat with salt.', 'Grill over charcoal.', 'Chop tomatoes and onions.', 'Serve with kachumbari.']),
                'category_id' => $categories['eastAfrican']->id,
                'region_id' => $regions['kenya']->id,
                'min_price' => '1200',
                'cook_time' => '60 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/Nyama-Choma.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Matapa',
                'description' => 'Mozambican stew made with cassava leaves, garlic, and coconut milk.',
                'ingredients' => json_encode(['cassava leaves', 'coconut milk', 'garlic', 'peanuts', 'shrimp']),
                'steps' => json_encode(['Boil cassava leaves.', 'Add coconut milk and garlic.', 'Mix in peanuts.', 'Cook shrimp and serve.']),
                'category_id' => $categories['southAfrican']->id,
                'region_id' => $regions['mozambique']->id,
                'min_price' => '800',
                'cook_time' => '40 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/Matapa.webp',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Tagine',
                'description' => 'Moroccan stew made with meat and dried fruits.',
                'ingredients' => json_encode(['lamb', 'apricots', 'onions', 'spices', 'almonds']),
                'steps' => json_encode(['Marinate lamb with spices.', 'Fry onions.', 'Add apricots and simmer.', 'Garnish with almonds.']),
                'category_id' => $categories['northAfrican']->id,
                'region_id' => $regions['morocco']->id,
                'min_price' => '1300',
                'cook_time' => '90 min',
                'prep_time' => '30 min',
                'image_path' => 'recipes/tagine.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Strawberry Milkshake',
                'description' => 'A creamy and sweet beverage made with fresh strawberries and milk.',
                'ingredients' => json_encode(['strawberries', 'milk', 'ice cream', 'sugar']),
                'steps' => json_encode(['Blend strawberries with milk.', 'Add ice cream.', 'Sweeten to taste.', 'Serve chilled.']),
                'category_id' => $categories['drinks']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '500',
                'cook_time' => '0 min',
                'prep_time' => '5 min',
                'image_path' => 'recipes/strawberry.webp',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Beignets Manioc',
                'description' => 'Cassava fritters common in Central Africa.',
                'ingredients' => json_encode(['cassava', 'flour', 'sugar', 'oil', 'water']),
                'steps' => json_encode(['Grate cassava.', 'Mix with flour and sugar.', 'Fry in hot oil.', 'Drain and serve.']),
                'category_id' => $categories['snacks']->id,
                'region_id' => $regions['centralAfrican']->id,
                'min_price' => '200',
                'cook_time' => '20 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/accracasava.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Kelewele',
                'description' => 'Spicy fried plantains popular in Ghana.',
                'ingredients' => json_encode(['plantains', 'ginger', 'chili', 'oil', 'salt']),
                'steps' => json_encode(['Slice plantains.', 'Marinate with spices.', 'Fry in hot oil.', 'Drain and serve.']),
                'category_id' => $categories['snacks']->id,
                'region_id' => $regions['ghana']->id,
                'min_price' => '300',
                'cook_time' => '15 min',
                'prep_time' => '10 min',
                'image_path' => 'recipes/kelewele.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Tiramisu',
                'description' => 'Classic Italian dessert with coffee and mascarpone.',
                'ingredients' => json_encode(['mascarpone', 'coffee', 'ladyfingers', 'cocoa', 'sugar']),
                'steps' => json_encode(['Dip ladyfingers in coffee.', 'Layer with mascarpone.', 'Chill overnight.', 'Dust with cocoa.']),
                'category_id' => $categories['desserts']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '1500',
                'cook_time' => '0 min',
                'prep_time' => '30 min',
                'image_path' => 'recipes/tiramisu.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Crepes Suzette',
                'description' => 'French crepes flambéed in orange liqueur.',
                'ingredients' => json_encode(['flour', 'eggs', 'orange juice', 'butter', 'liqueur']),
                'steps' => json_encode(['Make crepe batter.', 'Cook crepes.', 'Prepare orange sauce.', 'Flambé and serve.']),
                'category_id' => $categories['desserts']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '1200',
                'cook_time' => '20 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/CrepesSuzette.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Tapioca Pudding',
                'description' => 'Chilled dessert with tapioca pearls and coconut milk.',
                'ingredients' => json_encode(['tapioca pearls', 'coconut milk', 'sugar', 'vanilla']),
                'steps' => json_encode(['Soak tapioca pearls.', 'Boil with coconut milk.', 'Sweeten and cool.', 'Serve chilled.']),
                'category_id' => $categories['desserts']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '600',
                'cook_time' => '20 min',
                'prep_time' => '10 min',
                'image_path' => 'recipes/tapioca-Pudding.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Naan & Butter Chicken',
                'description' => 'Indian bread served with creamy spiced chicken.',
                'ingredients' => json_encode(['chicken', 'naan', 'tomatoes', 'cream', 'spices']),
                'steps' => json_encode(['Cook chicken with spices.', 'Make tomato sauce.', 'Add cream.', 'Serve with naan.']),
                'category_id' => $categories['international']->id,
                'region_id' => $regions['india']->id,
                'min_price' => '1300',
                'cook_time' => '40 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/naan-butter-chicken.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Pho',
                'description' => 'Vietnamese noodle soup with herbs and beef.',
                'ingredients' => json_encode(['rice noodles', 'beef', 'broth', 'herbs', 'lime']),
                'steps' => json_encode(['Cook noodles.', 'Prepare broth.', 'Slice beef thinly.', 'Assemble and serve.']),
                'category_id' => $categories['international']->id,
                'region_id' => $regions['vietnam']->id,
                'min_price' => '1000',
                'cook_time' => '60 min',
                'prep_time' => '30 min',
                'image_path' => 'recipes/pho.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Bun Kabab',
                'description' => 'Pakistani street food burger with spicy patty.',
                'ingredients' => json_encode(['beef patty', 'bun', 'chutney', 'tomatoes', 'onions']),
                'steps' => json_encode(['Make spicy patty.', 'Grill patty.', 'Assemble bun.', 'Add chutney and serve.']),
                'category_id' => $categories['international']->id,
                'region_id' => $regions['pakistan']->id,
                'min_price' => '500',
                'cook_time' => '15 min',
                'prep_time' => '15 min',
                'image_path' => 'recipes/Bun-Kabab.jpg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Couscous Royal',
                'description' => 'North African couscous served with meat and vegetables.',
                'ingredients' => json_encode(['couscous', 'lamb', 'carrots', 'chickpeas', 'spices']),
                'steps' => json_encode(['Steam couscous.', 'Cook lamb and vegetables.', 'Add spices.', 'Serve together.']),
                'category_id' => $categories['northAfrican']->id,
                'region_id' => $regions['algeria']->id,
                'min_price' => '1300',
                'cook_time' => '60 min',
                'prep_time' => '30 min',
                'image_path' => 'recipes/CouscousRoyal.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Pancakes',
                'description' => 'Sweet and crispy pancakes, a popular breakfast.',
                'ingredients' => json_encode(['flour', 'eggs', 'milk', 'sugar', 'butter']),
                'steps' => json_encode(['Mix batter ingredients.', 'Heat pan.', 'Pour batter and cook.', 'Serve with syrup.']),
                'category_id' => $categories['breakfasts']->id,
                'region_id' => $regions['international']->id,
                'min_price' => '300',
                'cook_time' => '15 min',
                'prep_time' => '10 min',
                'image_path' => 'recipes/pancakes.jpeg',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Ndomba',
                'description' => 'Steamed fish with local spices wrapped in banana leaves.',
                'ingredients' => json_encode(['fish', 'spices', 'banana leaves', 'tomatoes', 'onions']),
                'steps' => json_encode(['Season fish.', 'Wrap in banana leaves.', 'Steam with tomatoes.', 'Serve hot.']),
                'category_id' => $categories['littoral']->id,
                'region_id' => $regions['littoral']->id,
                'min_price' => '900',
                'cook_time' => '40 min',
                'prep_time' => '20 min',
                'image_path' => 'recipes/ndomba.webp',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
            [
                'title' => 'Kondre',
                'description' => 'Hearty spiced plantain and meat stew.',
                'ingredients' => json_encode(['plantains', 'beef', 'palm oil', 'onions', 'spices']),
                'steps' => json_encode(['Boil plantains.', 'Cook beef with onions.', 'Add palm oil and spices.', 'Simmer and serve.']),
                'category_id' => $categories['west']->id,
                'region_id' => $regions['west']->id,
                'min_price' => '1000',
                'cook_time' => '50 min',
                'prep_time' => '25 min',
                'image_path' => 'recipes/kondre.webp',
                'user_id' => $user->id,
                'visible_on' => 'both',
            ],
        ];

        foreach ($recipes as $recipeData) {
            Recipe::create($recipeData);
        }
    }
}
